// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingList.DBContext;

namespace ShoppingList.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    [Migration("20190521194710_added-ownedtype")]
    partial class addedownedtype
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppingList.Models.BuyList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("BuyList");
                });

            modelBuilder.Entity("ShoppingList.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("UnitPrice");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("ShoppingList.Models.FoodCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyListId");

                    b.Property<int>("Counter");

                    b.Property<int>("FoodId");

                    b.Property<DateTime>("Modification")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 5, 21, 21, 47, 9, 283, DateTimeKind.Local));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("BuyListId");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodCounters");
                });

            modelBuilder.Entity("ShoppingList.Models.FoodMessageRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Creation");

                    b.Property<int>("FoodId");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodMessageRating");
                });

            modelBuilder.Entity("ShoppingList.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("FoodMessageRating");
                });

            modelBuilder.Entity("ShoppingList.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Stars");

                    b.HasKey("Id");

                    b.ToTable("FoodMessageRating");
                });

            modelBuilder.Entity("ShoppingList.Models.BuyList", b =>
                {
                    b.OwnsOne("ShoppingList.Models.CreationBuylist", "CreationBuylist", b1 =>
                        {
                            b1.Property<int>("BuyListId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Creator");

                            b1.Property<DateTime>("OrderDate");

                            b1.ToTable("BuyList");

                            b1.HasOne("ShoppingList.Models.BuyList")
                                .WithOne("CreationBuylist")
                                .HasForeignKey("ShoppingList.Models.CreationBuylist", "BuyListId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("ShoppingList.Models.FoodCounter", b =>
                {
                    b.HasOne("ShoppingList.Models.BuyList", "BuyList")
                        .WithMany("shoppingList")
                        .HasForeignKey("BuyListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShoppingList.Models.Food", "Foods")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShoppingList.Models.FoodMessageRating", b =>
                {
                    b.HasOne("ShoppingList.Models.Food", "Foods")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShoppingList.Models.Messages", b =>
                {
                    b.HasOne("ShoppingList.Models.FoodMessageRating", "FoodMessageRating")
                        .WithOne("Messages")
                        .HasForeignKey("ShoppingList.Models.Messages", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShoppingList.Models.Rating", b =>
                {
                    b.HasOne("ShoppingList.Models.FoodMessageRating", "FoodMessageRating")
                        .WithOne("Rating")
                        .HasForeignKey("ShoppingList.Models.Rating", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
